### ISSUE TITLE
Cannot format time properly unless using your directives

### ISSUE THREAD

**Issue by aaronksaunders** [rajeshwarpatlolla/ionic-timepicker#21]
I have tried repeatedly to use the picker without your directives for formatting the resulting time and it never work correctly... Is it possible for you to add a sample that does not require your `standardTimeNoMeridian` and `standardTimeMeridian` directives? Or just embed them as options for the timePicker?

**Comment by rajeshwarpatlolla** [comment]
As i mentioned in the description, the current time picker only supports UTC time. The standard way is to pass the epoch time. If you want to convert the time from epoch to other format, then you can use any of my directive.
Could you please show me your code? So that i can get exact idea of how you want to use my component.
