### ISSUE TITLE
Minutes displays 0 instead of 00 and 12 hour format shows 00 AM

### ISSUE THREAD

**Issue by loomtronic** [rajeshwarpatlolla/ionic-timepicker#23]
I would expect this to say 00 not just 0 for the minutes

![image](https://cloud.githubusercontent.com/assets/1706404/7552938/b02704fa-f688-11e4-84c3-daa4b08cf1cf.png)

And this seems like it should say 12:00 AM not 00:00 AM

![image](https://cloud.githubusercontent.com/assets/1706404/7552936/a42d4f42-f688-11e4-8d3d-249c2067bb0f.png)

If you have any pointers to get this working that would be great, it's a great plugin!

**Comment by rajeshwarpatlolla** [comment]
When you select 12:00 AM, it will show 00:00 AM on the button, because we are manipulating with epoch time. You can create a directive to show 12 : 00 AM. 
When the time is 12:00 AM now it will show 12:00 AM instead of 12:0 AM. Zero will be added in front of the value, if the current value is less than 10.  
This issue has been fixed. Pull from develop to get the latest changes.

**Comment by loomtronic** [comment]
That works great when changing the value, but when I load the timepicker initially it still only shows one 0
