### ISSUE TITLE
Failed to instantiate module ionic-timepicker

### ISSUE THREAD

**Issue by ghost** [rajeshwarpatlolla/ionic-timepicker#42]
When I inject the dependency ionic-timepicker to the app module, it get this console error:
`Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic-timepicker due to:
Error: [$injector:nomod] Module 'ionic-timepicker' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.13/$injector/nomod?p0=ionic-timepicker`

And my whole app went blank... why is that?

**Comment by rajeshwarpatlolla** [comment]
Could you please check whether you have imported the `ionic-timepicker.js` file in the index.html? Also please cross check whether you have followed the instruction as per the description.

**Comment by ghost** [comment]
Yes I do have that, and I have followed each instruction in order as described...

**Comment by rajeshwarpatlolla** [comment]
Could you please test whether you have given the file path correctly? There are instances, where the bower components might be installed in to `bower_components` folder instead of `lib` folder. Also please re start the serve once. And also please cross check whether the file is loading or not in the `Network` tab of developer tools. You can search the file name there. If it is there, could you please confirm whether you are getting any errors on the console, except the previous one like file not found or some thing else?

**Comment by ghost** [comment]
I have restarted the serve and my computer as well...
The lib folder does contain the js files, and in the Network tab both js files are loaded with 304 status. 
There are two errors on the console other than the one mentioned previously:
I got `Uncaught ReferenceError: angular is not defined` for each of the js files(templates and  ionic-timepicker.js)

**Comment by rajeshwarpatlolla** [comment]
If you are getting the error `Uncaught ReferenceError: angular is not defined`, it means that angular is not yet available to `ionic-timepicker`. Please load the `ionic-timepicker.js` file after the `ionic.bundle.min.js` only. And also try changing the order of injection of `ionic-timepicker` after the `ionic`.

**Comment by ghost** [comment]
Oops...my bad. I had the incorrect order there...thanks for your help
The plugin works and looks excellent

**Comment by rajeshwarpatlolla** [comment]
Thanks for using it.
