### ISSUE TITLE
Set time to current time at popup time picker

### ISSUE THREAD

**Issue by aishahismail** [rajeshwarpatlolla/ionic-timepicker#53]
Right now, when I click the button to change the time, the popup showed the current hour, let's say right now is 03:30 PM, but the popup showed only 03:00 PM. So where can I adjust the default time? I had changed it before at .directive, but it still got the same output. Thanks for help.

**Comment by rajeshwarpatlolla** [comment]
Yes, it takes the current hour. It won't pick the in between minutes like 3:15 or 3:30 etc. It takes 3:00 or 4:00 etc.

But as per your suggestion i have added that feature, so that it will pick the current time. Let's say if the current time is **13:14**, then it will use the same time when you click on the button.

Also you can pass the time as shown below, so that it will pick the current hours and minutes. If ignore this `inputEpochTime` property then i t will pick the current hours and minutes, but it won't be shown on the button, until you select some time.

```
$scope.timePickerObject12Hour = {
      inputEpochTime: ((new Date()).getHours() * 60 * 60) + ((new Date()).getMinutes() * 60),  //Optional
      ....
};
```

Please take a look at [this commit](https://github.com/rajeshwarpatlolla/ionic-timepicker/commit/ae9293c4c05cf6ba49d75e54daffd6ef5b69254d)

**Comment by aishahismail** [comment]
it works! thanks for help
